name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Export Secret to JSON
        run: 'echo "$GOOGLE_TOKEN" > terraform-sa-key.json'
        env:
          GOOGLE_TOKEN: ${{secrets.GOOGLE_TOKEN}}
      
      - name: Run Terraform Init:
        run: make terraform-init
      
      - name:
        run: make terraform-plan