name: "Terraform"

on:
  push:
    branches:
      - main
      - stage
      - dev
  #Comment out these lines for the github action to run on push

env:
  GCP_PROJECT_ID: terraform-test-316516
  GCS_BUCKET: ericjm24-temp-bucket

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV
        run: |
          if [ ${GITHUB_REF##*/} = "main" ]
            then
              echo "ENV=prod" >> $GITHUB_ENV
          elif [ ${GITHUB_REF##*/} = "stage" ]
            then
              echo "ENV=stage" >> $GITHUB_ENV
          else
              echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install jinja2
          python build_vendor_lib.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install GCloud and export credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_TOKEN}}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true
          credentials_file_path: ${{github.workspace}}/terraform/terraform-sa-key.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1
      
      # - name: Zip Env Scripts
      #   uses: papeloto/action-zip@v1
      #   with:
      #     files: ./vendors/
      #     dest: lib.zip
      
      - name: Zip sftp-mover
        uses: papeloto/action-zip@v1
        with:
          files: ./sftp-mover/
          dest: sftp_mover.zip
      
      # - name: Upload Zip Env scripts
      #   run: gsutil cp lib.zip gs://${{env.GCS_BUCKET}}/${{env.ENV}}/
      
      - name: Upload Zipped sftp-mover
        run: gsutil cp sftp_mover.zip gs://${{env.GCS_BUCKET}}/${{env.ENV}}/

      - name: Init
        run: cd terraform && terraform init -reconfigure

      - name: Plan
        run: make terraform-plan
      
      - name: Deploy
        run: make terraform-apply
