name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: terraform-test-316516

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - run: echo "WORKDIR=$PWD" >> $GITHUB_ENV

      - name: Install GCloud and export credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GOOGLE_TOKEN}}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
          credentials_file_path: ${{ format('{0}/app/terraform/terraform-sa-key.json', env.WORKDIR) }}
      
      - run: ls

      - name: First init
        run: cd app/terraform && terraform workspace select dev && terraform init -reconfigure