name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: terraform-test-316516

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install GCloud and export credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_TOKEN}}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
          credentials_file_path: ${{github.workspace}}/app/terraform/terraform-sa-key.json

      - name: Set ENV
        run: echo "ENV=dev" >> $GITHUB_ENV

      - name: Initialize
        run: cd app/terraform && terraform init -reconfigure

      - name: Plan
        run: >
          cd app/terraform &&
          terraform workspace select ${{env.ENV}} && 
          terraform apply 
          -auto-approve 
          -var-file="./environments/${{env.ENV}}/config.tfvars" 
          -var-file="./environments/common.tfvars"

      - name: Deploy
        run: make terraform-apply