name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: terraform-test-316516

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Print out
        run: $GITHUB_REF
      # - name: Set ENV
      #   run: |-
      #     case ${GITHUB_REF##*/} in
      #       stage)
      #         echo "ENV=stage" >> $GITHUB_ENV
      #       main)
      #         echo "ENV=prod" >> $GITHUB_ENV
      #       *)
      #         echo "ENV=dev" >> $GITHUB_ENV
      #       esac
      
      # - name: Print ENV
      #   run: echo ${{env.ENV}}
      
      # - name: Checkout Repo
      #   uses: actions/checkout@v2

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1

      # - name: Install GCloud and export credentials
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     service_account_key: ${{ secrets.GOOGLE_TOKEN}}
      #     project_id: ${{ env.PROJECT_ID }}
      #     export_default_credentials: true
      #     credentials_file_path: ${{github.workspace}}/terraform/terraform-sa-key.json

      # - name: Init
      #   run: cd terraform && terraform init -reconfigure

      # - name: Plan
      #   run: make terraform-plan
      
      # - name: Deploy
      #   run: make terraform-apply
      
      # - name: Docker Build
      #   run: make docker-build
      
      # - name: Docker Push
      #   run: gcloud auth configure-docker && make docker-push
      
      # - name: Docker Deploy
      #   run: make docker-deploy